# Generated by Django 5.1.4 on 2025-01-14 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('rule_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(blank=True)),
                ('lastUpdate', models.DateTimeField(blank=True)),
                ('severity', models.IntegerField(blank=True)),
                ('status', models.BooleanField(blank=True)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'rule',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('username', models.TextField(blank=True, max_length=32)),
                ('severity_amount', models.IntegerField(blank=True)),
                ('status', models.BooleanField(blank=True)),
                ('role_id', models.IntegerField(blank=True, null=True)),
                ('password', models.TextField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('violation_id', models.IntegerField(blank=True, primary_key=True, serialize=False, unique=True)),
                ('user_id', models.IntegerField(blank=True)),
                ('rule_id', models.IntegerField(blank=True)),
                ('timestamp', models.DateTimeField(blank=True)),
            ],
            options={
                'db_table': 'violation',
                'managed': False,
            },
        ),
    ]
